@Yoomoney_HostAddress = http://localhost:5068

POST {{Yoomoney_HostAddress}}/api/v1/invoices
Accept: application/json
Content-Type: application/json

{
    "AccountId": "1583f5c0-ec74-4bd6-8ab3-179d877f9070",
    "Amount": 100.50
}

###

GET {{Yoomoney_HostAddress}}/api/v1/invoices?accountId=1583f5c0-ec74-4bd6-8ab3-179d877f9070&page=1&pageSize=10
Accept: application/json
