@Yoomoney_HostAddress = http://localhost:5068

POST {{Yoomoney_HostAddress}}/invoices
Accept: application/json
Content-Type: application/json

{
  "AccountId": "d48f6448-3fe4-4898-91ce-db79b5f57c9a",
  "Amount": 100.50
}

###
